string = 'GTCGTGCCTCGTGCCTCGTGCCATCGTGCCCGCTTCGTGCCTGATCGTGCCTCGTGCCTCGTGCCATGTCGTGCCTCGTGCCGGGGCGTAGGTCGTGCCTCGTGCCATGAGGATTCGTGCCGCTCGTCGTGCCTCGTGCCCTCGTGCCGTCGTGCCTCGGCTCGTGCCCCAGTCGTGCCTCGTGCCCTCGTGCCATCGTGCCCACAAAACATCGTGCCTTCGTGCCGTCGTGCCTGGTTCGTGCCTTCGTGCCCATCGTGCCTCGTGCCTCGTGCCTGGAGCAGCAATCGTGCCTCGTGCCGTGTCGTGCCGTACTCCGGAATTTCAAACGGACAGTCGTGCCCCGCTCGTGCCACTGTCGTGCCATCGTGCCCTGTCGTGCCCTCGTGCCCTCGTGCCCTTCGTGCCTCGTGCCTCGTGCCCTCGTGCCTCGTGCCTCGTGCCCTCGTGCCTCGTGCCTATCGTGCCCTCTTGGGTTCGTGCCTACTCGTGCCAGTCGTGCCTCGTGCCCCATCGTGCCTCACCGTAATCGTGCCGAATCGTGCCTCGTGCCTGCGACCGAGACATACCTCGTGCCCCAAATCGTGCCCGGTCGTGCCTCGTGCCCTCGTGCCCCTCGTGCCACCGTCGTGCCTCGTGCCATCGTGCCTTCGTGCCTGCTTCGTGCCATCGTGCCTCGTGCCTAGCTCGTGCCTTCGTGCCTCGTGCCTCGTGCCTCGTGCCTTCGTGCCTCGTGCCGCCTCGTGCCTCGTGCCGGTCGTGCCGTCGTGCCTCGTGCCTATCGTGCCTCGTGCCTCGTGCCTCGTGCCTGGTCGTGCCTCGTGCCGTCGTGCCTCACTCGTGCC'

substring = 'TCGTGCCTC'

res = [string[i:i+len(substring)] for i in range(len(string))]
print(res)

indices = [i+1 for i, x in enumerate(res) if x == substring]
indexes = []

for i in range(len(res)):
    if res[i] == substring:
        indexes.append(str(i + 1))

indexes = ' '.join(indexes)

print(indexes)
